[project]
name = "cogcom"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = "==3.11.13"
dependencies = [
    "bitsandbytes",
    "deepspeed==0.10.0",
    "einops==0.6.1",
    "gradio==3.50.2",
    "paddleocr==2.6.0.1",
    "pillow>=10.0.1",
    "pydantic==1.10.12",
    "seaborn>=0.13.0",
    "spacy>=3.8.7",
    "swissarmytransformer>=0.4.8",
    "timm>=0.9.12",
    "torch==2.2.0",
    "torchvision>=0.16.0",
    "transformers>=4.37.0",
    "wandb>=0.22.1",
    "xformers==0.0.24",
    "spacy>=3.6.0",
    "pip>=25.2",
    "click<=8.1",
    "num2words>=0.5.14",
    "numpy>=1.26.4",
    "pandas>=2.3.3",
    "en_core_web_sm @ https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-3.8.0/en_core_web_sm-3.8.0-py3-none-any.whl",
]

[dependency-groups]
dev = [
    "ruff>=0.14.1",
]

[tool.ruff]
# set the max line length to 79
line-length = 79

[tool.ruff.lint]
# ensure the “line-too-long” rule is enabled (E501)
select = ["ALL"]
extend-select = ["E501"]
ignore = [
  # docstring rule pairs are mutually exclusive
  # choose D213 (summary on second line) and ignore the opposite pair
  "D203", "D212",

  # formatter conflicts (Ruff’s docs recommend avoiding these with the formatter)
  "W191", "E111", "E114", "E117", "D206", "D300",
  "Q000", "Q001", "Q002", "Q003",
  "COM812", "COM819",
  "ISC001"  # some versions warn on this when formatting
]